# This is the general configuration files. Upon installation it will be copied to the
#  $BIOFLOWHOME fro the end user to edit and will be loaded from there, if found

# Specifies where the databases will be living locally and where they are to download
DB_locations:
  BIOGRID:
    local: $DB_HOME$/BioGRID/
    online: http://thebiogrid.org/downloads/archives/Release%20Archive/BIOGRID-3.3.122/BIOGRID-ORGANISM-3.3.122.tab2.zip
  COMPLEXPORTAL:
    local: $DB_HOME$/ComplexPortal
    online: ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/2020-12-16/complextab/9606.tsv,
      ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/2020-12-16/complextab/559292.tsv
  GO:
    local: $DB_HOME$/GO/
    online: http://purl.obolibrary.org/obo/go/go-basic.obo
    rename: go.obo
  HINT:
    local: $DB_HOME$/HiNT/
    online: http://hint.yulab.org/download/SaccharomycesCerevisiaeS288C/binary/hq/,
      http://hint.yulab.org/download/HomoSapiens/binary/hq/, http://hint.yulab.org/download/MusMusculus/binary/hq/
    rename: SaccharomycesCerevisiaeS288C_binary_hq.txt, HomoSapiens_binary_hq.txt,
      MusMusculus_binary_hq.txt
  PHOSPHOSITE:
    local: $DB_HOME$/PhosphoSite
    online: https://www.dropbox.com/s/76y22dec93rfr9f/Kinase_Substrate_Dataset?dl=1
    rename: Kinase_Substrate_Dataset
  REACTOME:
    local: $DB_HOME$/Reactome/
    online: http://www.reactome.org/download/current/biopax.zip
  TRRUST:
    local: $DB_HOME$/TFs/TRRUST
    online: http://www.grnpedia.org/trrust/data/trrust_rawdata.human.tsv, http://www.grnpedia.org/trrust/data/trrust_rawdata.mouse.tsv
  UNIPROT:
    local: $DB_HOME$/Uniprot/uniprot_sprot.dat
    online: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz

# Where bioflow will look for server interfaces. neo4j password has to be defined as an
# environment variable $NEO4JPASS (cf docs)
Servers:
  mongodb_server: mongodb://localhost:27017/
  neo4j_server: bolt://localhost:7687
  neo4j_user: 'neo4j'

# Configurations for different organisms.
# To change the organism, please comment out the active organism and uncomment the one you want

#Sources:  # Yeast  # TRACING: revert to the reference state, i.e. only yeast is active
#  BIOGRID:
#    name_pattern: Saccharomyces_cerevisiae
#  GO:
#    file: go.obo
#  HINT:
#    file: SaccharomycesCerevisiaeS288C_binary_hq.txt
#  INTERNAL:
#    compops: '15'
#    dumpprefix: /yeast
#    mongoprefix: _yeast
#    mongosuffix: _v_1
#    neo4jdb: yeast
#  META:
#    organism: Yeast
#  PHOSPHOSITE:
#    file: Kinase_Substrate_Dataset
#    organism: yeast
#  REACTOME:
#    file: Saccharomyces_cerevisiae.owl
#  UNIPROT:
#    tax_ids: 559292,

Sources:  # Human
  BIOGRID:
    name_pattern: Homo_sapiens
  COMPLEXPORTAL:
    file: 9606.tsv
  GO:
    file: go.obo
  HINT:
    file: HomoSapiens_binary_hq.txt
  INTERNAL:
    compops: '3'
    dumpprefix: /human
    mongoprefix: _human
    mongosuffix: _v_1
    neo4jdb: human
  META:
    organism: Human
  PHOSPHOSITE:
    file: Kinase_Substrate_Dataset
    organism: human
  REACTOME:
    file: Homo_sapiens.owl
  TRRUST:
    file: trrust_rawdata.human.tsv
    significance: '1'
  UNIPROT:
    tax_ids: '9606'

#Sources:   # Mouse. Not recommended - the data is really lacking
#  BIOGRID:
#    name_pattern: Mus_musculus
#  GO:
#    file: go.obo
#  HINT:
#    file: MusMusculus_binary_hq.txt
#  INTERNAL:
#    compops: '1'
#    dumpprefix: /mouse
#    mongoprefix: _mouse
#    mongosuffix: _v_1
#    neo4jdb: mouse
#  META:
#    organism: Mouse
#  PHOSPHOSITE:
#    organism: mouse
#  REACTOME:
#    file: Mus_musculus.owl
#  UNIPROT:
#    tax_ids: 10090,

# Configurations of variable the end user might want to change
User_Settings:
  smtp_logging:
    True
  smtp_logging_parameters:
    local_host:
      lpdpc35.epfl.ch
    local_mail_account:
      andrei@lpdpc35.epfl.ch
    reporting_target_mail:
      andrei.kucharavy@epfl.ch
  environment:
    skip_reactome:
      False
    skip_hint:
      False
    skip_biogrid:
      False
    use_background:
      True
    bki_filter:
      [biological_process,]
    bki_correlation_factors:
      [1, 1]
    bki_ultraspec_clean:   # Clean out annotation terms that are too specific
      True
    bki_ultraspec_lvl:  # Least proteins a term can annotate before it's considered too specific
      3
  solver:
    # those are deep configurations and should not be touched unless you know what you are doing:
    switch_to_splu:
      False  # switching this to True incurs approximately an 100-fold slowdown
    share_solver:
      True  # switching this to False incurs approximately a 50-fold slowdown
    line_loss: # This is the line loss for the approximate matrix inversion - basically the fudge for cholesky
      1e-10
  analysis:
    sparse_analysis_threshold:
      200  # number of proteins in analysis set at which we will be switching to sparse sampling
      # in sparse sampling mode, the number oif pairs sampled will be (this threshold)^2 / 2
    default_background_samples:
      24  # number of random samples we want to compare to by default
    # This is the p-value that is set by user and is to be propagated throughout the analyses.
    default_p_val_cutoff:
      0.2
    # This is the minimum nodes per degree used in p_value calculation
    min_nodes_for_p_val:
      10
  debug_flags:
    # those are mostly debug flags and should not be touched
    implicitely_threaded:
      True
    psutil_main_loop_memory_tracing:
      False  # controls the log_mem behavior in conduction_routines.py
    memory_source_allowed:
      False
    node_current_in_debug:
      False
  # Those are global variables that were used in order to check algorithm performance
  use_normalized_laplacian:
    False
  fraction_edges_dropped_in_laplacian:
    0.0
