version: "2"
services:
  neo4j:
    image: neo4j
    container_name: "neo4j_bioflow"
    restart: always
    expose:
      - 7474
      - 7687
    volumes:
      - $HOME/bioflow/docker-neo4j/db-data:/data
    environment:
      - NEO4J_AUTH=neo4j/1345
  mongodb:
    image: mongo
    container_name: "mongo_bioflow"
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - $HOME/bioflow/docker-mongo/db-data:/data/db
  bioflow:
    image: bioflow
    stdin_open: true
    tty: true
    environment:
      - NEOPASS=1345
      - NEO4URL=bolt://neo4j:7687
      - MONGOURL=mongodb://mongodb:27017/
    volumes:
      - $HOME/bioflow/source:/source
      - $HOME/bioflow/input:/input
      - $HOME/bioflow/input:/output
    depends_on:
      - mongodb
      - neo4j
    links:
      - mongodb
      - neo4j


