version: "3.2"
services:
  neo4j:
    image: neo4j
    container_name: "neo4j_bioflow"
    restart: always
    expose:
      - 7474
      - 7687
    volumes:
      - type: bind
        source: $HOME/bioflow/docker-neo4j/db-data
        target: "/data"
        bind:
          propagate: rshared
    environment:
      - NEO4J_AUTH=neo4j/1345
  mongodb:
    image: mongo
    container_name: "mongo_bioflow"
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - type: bind
        source: $HOME/bioflow/docker-mongo/db-data
        target: "/data/db"
        bind:
          propagate: rshared
  bioflow:
    image: bioflow
    stdin_open: true
    tty: true
    environment:
      - NEOPASS=1345
      - NEO4URL=bolt://neo4j:7687
      - MONGOURL=mongodb://mongodb:27017/
    volumes:
      - type: bind
        source: $HOME/bioflow/source
        target: /source
        bind:
          propagate: rshared
      - type: bind
        source: $HOME/bioflow/input
        target: /input
        bind:
          propagate: rshared
      - type: bind
        source: $HOME/bioflow/input
        target: /output
        bind:
          propagate: rshared
    depends_on:
      - mongodb
      - neo4j
    links:
      - mongodb
      - neo4j


