'''
Created on Aug 1, 2013

@author: andrei
'''

subdict2={
'Thymidylate synthase' : 'thymidylate synthase',
'alpha 2a adrenoceptor' : 'alpha-2a adrenoceptor',
'Nociceptin receptor' : 'nociceptin receptor',
'Retinoic acid receptor-gamma ' : 'retinoic acid receptor gamma',
'Peroxisome proliferator-activated receptor-gamma ' : 'peroxisome proliferator-activated receptor gamma',
'Pancreatic alpha -amylase' : 'pancreatic alpha-amylase',
'Pancreatic lipase' : 'pancreatic lipase',
'DOPA decarboxylase' : 'dopa decarboxylase',
'Epoxide hydrolase 1' : 'epoxide hydrolase 1',
'Thiazide-sensitive sodium-chloride cotransporter' : 'thiazide-sensitive sodium-chloride cotransporter',
'Histamine H2 receptor' : 'histamine h2 receptor',
'Arachidonate 5-lipoxygenase' : 'arachidonate 5-lipoxygenase',
'Carbonic anhydrase II' : 'carbonic anhydrase ii',
'4-hydroxyphenylpyruvate dioxygenase' : '4-hydroxyphenylpyruvate dioxygenase',
'HMG-CoA reductase' : 'hmg-coa reductase',
'alpha 1b adrenoceptor' : 'alpha-1b adrenoceptor',
'Dopamine D1 receptor' : 'dopamine d1 receptor',
'Butyrylcholine esterase' : 'butyrylcholine esterase',
'Progesterone receptor' : 'progesterone receptor',
'Dopamine D3 receptor' : 'dopamine d3 receptor',
'Glutamate receptor ionotropic, AMPA 1' : 'glutamate receptor ionotropic, ampa 1',
'Vascular endothelial growth factor receptor 1' : 'vascular endothelial growth factor receptor 1',
'Synaptic vesicular amine transporter' : 'synaptic vesicular amine transporter',
'Vascular endothelial growth factor receptor 3' : 'vascular endothelial growth factor receptor 3',
'Vascular endothelial growth factor receptor 2' : 'vascular endothelial growth factor receptor 2',
'Voltage-gated potassium channel subunit Kv4.3' : 'voltage-gated potassium channel subunit kv4.3',
'Peroxisome proliferator-activated receptor-alpha ' : 'peroxisome proliferator-activated receptor alpha',
'Ephrin type-A receptor 2' : 'ephrin type-a receptor 2',
'Type I iodothyronine deiodinase' : 'type i iodothyronine deiodinase',
'Equilibrative nucleoside transporter 1' : 'equilibrative nucleoside transporter 1',
'Cytochrome P450 3A3' : 'cytochrome p450 3a3',
'Acetylcholinesterase' : 'acetylcholinesterase',
'Retinoic acid receptor-beta ' : 'retinoic acid receptor beta',
'Cyclooxygenase 1' : 'cyclooxygenase-1',
'Cyclooxygenase 2' : 'cyclooxygenase-2',
'Adenosine deaminase' : 'adenosine deaminase',
'Lipoprotein lipase' : 'lipoprotein lipase',
'Adenine nucleotide translocator 1' : 'adenine nucleotide translocator 1',
'Farnesyl diphosphate synthase' : 'farnesyl diphosphate synthase',
'Potassium-transporting ATPase alpha -chain 1' : 'potassium-transporting atpase alpha chain 1',
'Tyrosine 3-hydroxylase' : 'tyrosine 3-hydroxylase',
'Tubulin beta 1 chain' : 'tubulin beta-1 chain',
'Mineralocorticoid receptor' : 'mineralocorticoid receptor',
'Dopamine D5 receptor' : 'dopamine d5 receptor',
'beta 2 adrenoceptor' : 'beta-2 adrenoceptor',
'Dopamine D4 receptor' : 'dopamine d4 receptor',
'Retinoic acid receptor-alpha ' : 'retinoic acid receptor alpha',
'Vasopressin V1B receptor' : 'vasopressin v1b receptor',
'Muscarinic acetylcholine receptor M1' : 'muscarinic acetylcholine receptor m1',
'Muscarinic acetylcholine receptor M3' : 'muscarinic acetylcholine receptor m3',
'Muscarinic acetylcholine receptor M2' : 'muscarinic acetylcholine receptor m2',
'Muscarinic acetylcholine receptor M5' : 'muscarinic acetylcholine receptor m5',
'Muscarinic acetylcholine receptor M4' : 'muscarinic acetylcholine receptor m4',
'Dihydrofolate reductase' : 'dihydrofolate reductase',
'Glutamate receptor ionotropic kainate 1' : 'glutamate receptor ionotropic, kainate 1',
'beta 1 adrenoceptor' : 'beta-1 adrenoceptor',
'Tyrosine-protein kinase YES' : 'tyrosine-protein kinase yes',
'Cysteinyl leukotriene receptor 1' : 'cysteinyl leukotriene receptor 1',
'Glucocorticoid receptor' : 'glucocorticoid receptor',
'HERG' : 'herg',
'alpha 2c adrenoceptor' : 'alpha-2c adrenoceptor',
'Tyrosine-protein kinase FYN' : 'tyrosine-protein kinase fyn',
'Thyroid hormone receptor-alpha ' : 'thyroid hormone receptor alpha',
'alpha 1a adrenoceptor' : 'alpha-1a adrenoceptor',
'Mu opioid receptor' : 'mu opioid receptor',
'Steroid 5-alpha -reductase 2' : 'steroid 5-alpha-reductase 2',
'alpha 2b adrenoceptor' : 'alpha-2b adrenoceptor',
'alpha 1d adrenoceptor' : 'alpha-1d adrenoceptor',
'Dopamine D2 receptor' : 'dopamine d2 receptor',
'Steroid 5-alpha -reductase 1' : 'steroid 5-alpha-reductase 1',
'Ceramide glucosyltransferase' : 'ceramide glucosyltransferase',
'Vitamin K epoxide reductase complex subunit 1' : 'vitamin k epoxide reductase complex subunit 1',
'Tubulin beta 2 chain' : 'tubulin beta-2 chain',
'Prostanoid EP2 receptor' : 'prostanoid ep2 receptor',
'gamma -amino-N-butyrate transaminase' : 'gamma-amino-n-butyrate transaminase',
'Cytochrome P450 19A1' : 'cytochrome p450 19a1',
'Ryanodine receptor 1' : 'ryanodine receptor 1',
'Ryanodine receptor 3' : 'ryanodine receptor 3',
'Catechol O-methyltransferase' : 'catechol o-methyltransferase',
'Gastric lipase' : 'gastric lipase',
'Tyrosine-protein kinase LCK' : 'tyrosine-protein kinase lck',
'FK506-binding protein 1A' : 'fk506-binding protein 1a',
'Cyclophilin B' : 'cyclophilin b',
'Cyclophilin A' : 'cyclophilin a',
'Vasopressin V1A receptor' : 'vasopressin v1a receptor',
'Voltage-gated potassium channel subunit Kv7.1' : 'voltage-gated potassium channel subunit kv7.1',
'Platelet-derived growth factor receptor-beta ' : 'platelet-derived growth factor receptor beta',
'Aldose reductase' : 'aldose reductase',
'Androgen receptor' : 'androgen receptor',
'Histamine H1 receptor' : 'histamine h1 receptor',
'Norepinephrine transporter' : 'norepinephrine transporter',
'Platelet-derived growth factor receptor-alpha ' : 'platelet-derived growth factor receptor alpha',
'Thyroid peroxidase' : 'thyroid peroxidase',
'Cytochrome P450 11A1' : 'cytochrome p450 11a1',
'Vasopressin V2 receptor' : 'vasopressin v2 receptor',
'Sulphonylurea receptor 1' : 'sulfonylurea receptor 1',
'Sulphonylurea receptor 2' :'sulfonylurea receptor 2',
'3-beta -hydroxysteroid dehydrogenase': '',         # Not really present in the Swissprot
'Inhibitor of nuclear factor-kappaB kinase beta -subunit':'inhibitor of nuclear factor kappa-b kinase subunit beta',
'Dihydroorotate dehydrogenase':['PYRD_HUMAN'],
'Epidermal growth factor receptor erbB1':'epidermal growth factor receptor',
'Thioredoxin reductase 1':'thioredoxin reductase tr1',
'Voltage-gated calcium channel alpha 2/delta  subunit 1': 'voltage-gated calcium channel subunit alpha-2/delta-1',
'Succinate semialdehyde dehydrogenase':'succinate-semialdehyde dehydrogenase, mitochondrial',
'delta -opioid receptor': 'delta-type opioid receptor',
'B-Raf proto-oncogene serine/threonine-protein kinase' : ['BRAF_HUMAN'],
'Angiotensin-converting enzyme':['ACE_HUMAN','ACE_HUMAN'],
'Ribonucleoside-diphosphate reductase M2 chain': 'ribonucleoside-diphosphate reductase subunit m2',
'Angiotensin II type 1A (AT1A) receptor': 'angiotensin ii type-1 receptor',
'Macrophage colony-stimulating factor receptor': 'macrophage colony-stimulating factor 1 receptor',
'Vitamin D receptor':'vitamin d3 receptor',
'Guanylate cyclase soluble beta 1 chain':'guanylate cyclase soluble subunit beta-1',
'Neuronal acetylcholine receptor protein beta 2':'neuronal acetylcholine receptor subunit beta-2',
'Phosphodiesterase 3A':'asm-like phosphodiesterase 3a',
'Endothelin receptor ETA':'endothelin a receptor',
'Phosphodiesterase 5A':['PDE5A_HUMAN'],
'Sodium channel protein type IV alpha -subunit':'sodium channel protein type iv subunit alpha',
'Inosine-5-monophosphate dehydrogenase 2':"inosine-5'-monophosphate dehydrogenase 2",
'Inositol-1(or 4)-monophosphatase A2':'inositol-1(or 4)-monophosphatase 2',
'Serotonin transporter':['SC6A4_HUMAN'],
'Sodium channel protein type V alpha -subunit':'sodium channel protein type v subunit alpha',
'Neuronal acetylcholine receptor protein alpha 4':'neuronal acetylcholine receptor subunit alpha-4',
'Neuronal acetylcholine receptor protein alpha 2':'neuronal acetylcholine receptor subunit alpha-2',
'Adenosine A1 receptor':'adenosine receptor a1',
'Adenosine A2A receptor':'adenosine receptor a2a',
'Sodium channel protein type I alpha -subunit':'sodium channel protein type i subunit alpha',
'Oestrogen receptor-alpha ':'estrogen-related receptor alpha',
'Melatonin receptor 1A':'melatonin receptor type 1a',
'Melatonin receptor 1B':'melatonin receptor type 1b',
'Sodium-(potassium)-chloride cotransporter 2':['S12A2_HUMAN'],
'Endothelin receptor ETB':'endothelin b receptor',
'Cannabinoid CB2 receptor':'cannabinoid receptor 2',
'Thyroid hormone receptor-beta 1':'thyroid hormone receptor beta',
'DNA topoisomerase IIalpha ':'dna topoisomerase 2-alpha',
'Adenosine A3 receptor':'adenosine receptor a3',
'Proto-oncogene tyrosine-protein kinase receptor RET':['RET_HUMAN'],
'Bile acid receptor FXR':['NR1H4_HUMAN'],
'Tyrosine-protein kinase receptor FLT3': ['FLT3_HUMAN'],
'Cannabinoid CB1 receptor':'cannabinoid receptor 1',
'Voltage-gated T-type calcium channel alpha 1H':'voltage-dependent t-type calcium channel subunit alpha-1h',
'Purinergic receptor P2Y12':['P2Y12_HUMAN'],
'sigma-opioid receptor':'sigma 1-type opioid receptor',
'Tyrosine-protein kinase ABL':'tyrosine-protein kinase abl1',
'Serotonin 1A (5-HT1A) receptor':['5HT1A_HUMAN'],
'Monoamine oxidase B':'monoamine oxidase type b',
'Serine/threonine-protein kinase RAF': ['RAF1_HUMAN'],
'Inosine-5-monophosphate dehydrogenase 1':"inosine-5'-monophosphate dehydrogenase 1",
'Cytochrome P450 11B1': ['C11B1_HUMAN'],
'Oestrogen receptor-beta ':'estrogen receptor beta',
'GABAB receptor 1':'gaba-b receptor 1',
'Glutamate (NMDA) receptor subunit epsilon 1':'glutamate [nmda] receptor subunit epsilon-1',
'Neurokinin 1 receptor':['NK2R_HUMAN'],
'Potassium channel, inwardly rectifying, subfamily J,':['IRK11_HUMAN'],
'kappa-opioid receptor':'kappa-type opioid receptor',
'Monoamine oxidase A':'monoamine oxidase type a',
'Sodium/potassium-transporting ATPase alpha 1 chain':'potassium-transporting atpase alpha chain 1',
'Aldehyde dehydrogenase':['AL3A2_HUMAN','AL3A1_HUMAN'],
'Adenosine A2B receptor':'adenosine receptor a2b',
'Dopamine transporter':['SC6A3_HUMAN'],
'Tyrosine-protein kinase SRC':['SRC_HUMAN'],
'Stem-cell growth factor receptor':'mast/stem cell growth factor receptor kit',
'Phosphodiesterase 4A':['PDE4A_HUMAN'],
'Serotonin 1D (5-HT1D) receptor':'serotonin 1d alpha receptor',
'Glutamate (NMDA) receptor subunit epsilon 2':'glutamate [nmda] receptor subunit epsilon-2',
'GABA transporter 1':['VIAAT_HUMAN'],
'Voltage-gated L-type calcium channel alpha 1C':['CAC1C_HUMAN'],
'Xanthine dehydrogenase':['XDH_HUMAN'],
'GABA receptor beta 2 subunit':['GBRB2_HUMAN'],
'Calcium-sensing receptor':['CASR_HUMAN'],
'Serotonin 2B (5-HT2B) receptor':['5HT2B_HUMAN'],
'NPC1L1':['NPCL1_HUMAN'],
'GABA receptor gamma 2 subunit':['GBRG2_HUMAN'],
'Vacuolar ATP synthase catalytic subunit A':['VATL_HUMAN'],
'Maltase-glucoamylase':['MGA_HUMAN'],
'Serotonin 1B (5-HT1B) receptor':['5HT1B_HUMAN'],
'Serotonin 1F (5-HT1F) receptor':['5HT1F_HUMAN'],
'Electrochemical nucleoside transporter':'', # Non-existent in UNIPORT
'Serotonin 3A (5-HT3A) receptor':['5HT3A_HUMAN'],
'Serotonin 4 (5-HT4) receptor':['5HT4_HUMAN'],
'Serotonin 2C (5-HT2C) receptor':['5HT2C_HUMAN'],
'Troponin C':['TNNI3_HUMAN','TNNC2_HUMAN'],
'GABA receptor alpha 1 subunit':['GBRR1_HUMAN'],
'Serotonin 2A (5-HT2A) receptor':['5HT2A_HUMAN'],
'Amiloride-sensitive sodium channel alpha -subunit':['ASIC2_HUMAN'],
'isoform 1':'',
'member 11':'',
'subunit':'',
}