'''
Created on 13 mai 2013

@author: Andrei Kucharavy
'''

from bulbs.model import Node, Relationship
from bulbs.property import String, Integer, Float
from bulbs.utils import current_datetime

class Protein(Node):
    element_type="protein"
    
    UniprotId=String(nullable=False)
    Location=String()
    Annotation=String() # Ideally should disappear: all calls to this field should be logged

class GOTerm(Node):
    element_type="goterm"
    
    GOTermID=String(nullable=False)
    FullName=String()

class Annotates(Relationship):
    #relation between a Protein and a GOTerm
    label = "annotates"
    
    confidence=Float() # between 0 for false to 1 for sure 

#Other classes are to be constructed in relation with the Reactome data structure

class Localization(Relationship):
    #Allows to link together the same protein in different cellular compartments 
    label="localizes"


class SmallMolecule(Node):
    element_type="small_mol"

    Id=String(nullable=False)
    
class Pathway(Node):
    # Can be a pathway step just as a whole pathway
    # TODO: define pathway granularity    
    element_type="Pathway"

    PathwayID=String(nullable=False)

class DNA(Node):
    element_type="DNA"
    
    Position=String()    
    
class Complex(Node):
    ement_type="Complex"
    
    Name=String(nullable=False)
    
class XREF_ACCESSION(Node):
    element_type="UNIPROT_ACCESSION"

class Litterature(Node):
    element_type="Litterature"
    
class Cell_Location(Node):
    element_type="Cell_Location"

class AtomicReaction(Node):
    element_type="Atomic_reaction"
    
class RNA(Node):
    element_type="RNA"

class Modification(Node):
    element_type="Modification"
    #Mutation or post-translational modification

class Prot_Fragment(Node):
    element_type="Prot_Fragment"

class DNA_Fragment(Node):
    element_type="DNA_Fragment"

class RNA_Fragment(Node):
    element_type="RNA_Fragment"

class Isoform(Node):
    element_type="Isoform"
    # Generated by alternative splicing